version: '3.8'
services:
  hse-perm-helper-backend:
    image: melowetty/hse-perm-helper-backend
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/home/gradle/project/build
    expose:
      - "$SPRING_LOCAL_PORT"
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRESDB_LOCAL_PORT/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_SECURITY_PRIVATE-KEY=$PRIVATE_KEY
      - SERVER_PORT=$SPRING_LOCAL_PORT
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://$SERVICE_DISCOVERY_USER:$SERVICE_DISCOVERY_PASSWORD@$SERVICE_DISCOVERY_HOST:$SERVICE_DISCOVERY_PORT/eureka
    restart: always
    networks:
      - internal
      - service-discovery_internal
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    expose:
      - "$POSTGRESDB_LOCAL_PORT"
    volumes:
      - db:/var/lib/postgres
    networks:
      - internal
volumes:
  db:
networks:
  internal:
  service-discovery_internal:
    external: true
