package com.melowetty.hsepermhelper.notification.verification

import com.melowetty.hsepermhelper.notification.KafkaNotificationV2
import com.melowetty.hsepermhelper.notification.NotificationType

class EmailIsVerifiedNotification: KafkaNotificationV2(NotificationType.EMAIL_IS_VERIFIED)
